### ISSUE TITLE
Fix Dark Reader

### ISSUE THREAD

**Issue by SoloFlighter101** [flirtual/flirtual#101]
### Describe the issue

I can't use Dark Reader on Flirtual for some reason. All I can change is the site fonts.

### To reproduce

Install Dark Reader for your browser
Go to Flirtual

### What platform are you seeing this problem on?

All Dark Reader supported browsers

### Additional context

Aries, I love you ❤❤❤

**Comment by kfarwell** [comment]
This is a feature.

**Comment by SoloFlighter101** [comment]
awww I wanted to mess with Aries more
