### ISSUE TITLE
useShare improvements

### ISSUE THREAD

**Issue by kfarwell** [flirtual/flirtual#132]
- [x] Also copy the link to clipboard + toast (some platforms don't support sharing or don't have a copy option in the share UI)
- [x] "Abort due to cancellation of share" error toast is scary and unnecessary

**Comment by kfarwell** [comment]
Should display "Copied to clipboard" toast even when sharing is supported, since some systems don't support copying to clipboard from the share dialog.

**Comment by LavenderFoxxo** [comment]
@kfarwell Would you possibly be able to provide a bit more clarification in regards to this issue. When you say display the toast even when sharing isn't supported, do you mean remove the function that checks if `canShare` returns false? Surely it can't be as simple as that

**Comment by kfarwell** [comment]
@LavenderFoxxo It's as simple as that! :) Just drop the early return too so the share still happens.
