### ISSUE TITLE
Client side error/crash while browsing homies

### ISSUE THREAD

**Issue by AmaliaKalio** [flirtual/flirtual#172]
### Describe the issue

While going through homies, the application crashes with `Application error: a client-side exception has occurred (see the browser console for more information).`

![image](https://github.com/flirtual/flirtual/assets/9390932/4094ed76-3181-4ddc-8187-e67611ef465f)

### To reproduce

1. Go to Homies
2. Click on 'x' a few times
3. ???
4. Crash

### What platform are you seeing this problem on?

Version 126.0.6478.8 (Official Build) beta (64-bit), Windows 11 Pro x64

**Comment by AmaliaKalio** [comment]
The error has changed to the following.
![image](https://github.com/flirtual/flirtual/assets/9390932/5d40f8ae-3915-4543-b51b-14246962ac88)

**Comment by AmaliaKalio** [comment]
Marking resovled, as this doesn't seem to be occurring anymore.

**Comment by kfarwell** [comment]
👍 I believe these errors are being caused by intermittent outages with an upstream host. They are brief but have become somewhat frequent recently. Haven't had time to investigate closely but hope to soon.

Thanks for reporting!
