### ISSUE TITLE
"Other" -> "Other genders"

### ISSUE THREAD

**Issue by kfarwell** [flirtual/flirtual#83]
* [x] /settings/matchmaking & /onboarding/1: *I want to meet…*
* [x] /settings/tags & /onboarding/2: Gender checkbox

**Comment by marth141** [comment]
What is the progress on this and where are some good places to start working on this?

**Comment by kfarwell** [comment]
@marth141 Thanks for your interest! This change has been implemented along with some larger onboarding updates and just hasn't been committed yet.

Issues with the [project](https://github.com/orgs/flirtual/projects/7) status "Todo" or "Backlog" are up for grabs - happy to help you get started from there if one catches your eye, or feel free to drop by the #developers channel in our [Discord](https://discord.gg/flirtual)!

**Comment by marth141** [comment]
All good! I'll keep looking around issues and will for sure be on the developers channel.
