### ISSUE TITLE
Some common profile tags are not highlighted

### ISSUE THREAD

**Issue by kfarwell** [flirtual/flirtual#97]
Some tags on profile are not highlighted pink when you have them in common with someone.

- [ ] Open to serious dating
- [ ] Dom/sub/switch (dom/sub should highlight opposite, switch should highlight same)
- [ ] Monogamous/non-monogamous

**Comment by matortheeternal** [comment]
I'll give this a shot.

**Comment by ariesclark** [comment]
> I'll give this a shot.

Thanks for the contribution!
