### ISSUE TITLE
Typing and removing a custom interest removes all custom interests

### ISSUE THREAD

**Issue by kfarwell** [flirtual/flirtual#98]
1. Add a custom interest to your profile normally and press Update
2. Type in another custom interest and press enter
3. Press backspace to remove the new interest
4. Press Update

All of your custom interests are removed from your profile.

**Comment by matortheeternal** [comment]
I'll look into this issue and see if I can make a fix.

**Comment by matortheeternal** [comment]
well, I think that initial assessment was wrong.  I'm looking at the request payload after going through this flow and it looks completely normal, so I think this bug must actually be on the backend.  I'll see if I can figure it out.  o7
